services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app/__init__.py
      SECRET_KEY: talentum2024
      WEATHER_DATA_PATH: data/weather.json


  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development